name: CADD-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - openbabel
  - nglview
  - plotly
  - rdkit
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
jupyter-nbextension enable nglview --py --sys-prefix
